<a href="https://colab.research.google.com/github/RNSHDeepika7/Assignments/blob/main/EDA2_assgnt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import files
uploaded=files.upload()

Saving adult_with_headers.csv to adult_with_headers.csv

In [4]:
import pandas as pd
df=pd.read_csv("adult_with_headers.csv")
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [5]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [6]:
# Replace missing values with a specific value.
df.fillna(0, inplace=True)

In [7]:
df.dtypes

age                int64
workclass         object
fnlwgt             int64
education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

In [8]:
#applying standard scaling to numerical variables

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit the scaler to the numerical columns
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns
df[numerical_columns] = scaler.fit_transform(df[numerical_columns])

# Print the transformed DataFrame
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.030671,State-gov,-1.063611,Bachelors,1.134739,Never-married,Adm-clerical,Not-in-family,White,Male,0.148453,-0.21666,-0.035429,United-States,<=50K
1,0.837109,Self-emp-not-inc,-1.008707,Bachelors,1.134739,Married-civ-spouse,Exec-managerial,Husband,White,Male,-0.145920,-0.21666,-2.222153,United-States,<=50K
2,-0.042642,Private,0.245079,HS-grad,-0.420060,Divorced,Handlers-cleaners,Not-in-family,White,Male,-0.145920,-0.21666,-0.035429,United-States,<=50K
3,1.057047,Private,0.425801,11th,-1.197459,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,-0.145920,-0.21666,-0.035429,United-States,<=50K
4,-0.775768,Private,1.408176,Bachelors,1.134739,Married-civ-spouse,Prof-specialty,Wife,Black,Female,-0.145920,-0.21666,-0.035429,Cuba,<=50K

*  Standard scaling is preferred when the distribution of the feature values is approximately Gaussian (normal distribution).
*   Linear models like Linear Regression, Logistic Regression, and Support Vector Machines (SVM) that assume features are normally distributed and have equal variances.
*   Linear models like Linear Regression, Logistic Regression, and Support Vector Machines (SVM) that assume features are normally distributed and have equal variances.

In [15]:
import pandas as pd
df=pd.read_csv("adult_with_headers.csv")
df

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [16]:
# applying minmax scaler for numerical variables

from sklearn.preprocessing import MinMaxScaler

# Create a MinMaxScaler object
minmax_scaler = MinMaxScaler()

# Fit the scaler to the numerical columns
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns
df[numerical_columns] = minmax_scaler.fit_transform(df[numerical_columns])

# Print the transformed DataFrame
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,0.301370,State-gov,0.044302,Bachelors,0.800000,Never-married,Adm-clerical,Not-in-family,White,Male,0.02174,0.0,0.397959,United-States,<=50K
1,0.452055,Self-emp-not-inc,0.048238,Bachelors,0.800000,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.00000,0.0,0.122449,United-States,<=50K
2,0.287671,Private,0.138113,HS-grad,0.533333,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.00000,0.0,0.397959,United-States,<=50K
3,0.493151,Private,0.151068,11th,0.400000,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.00000,0.0,0.397959,United-States,<=50K
4,0.150685,Private,0.221488,Bachelors,0.800000,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.00000,0.0,0.397959,Cuba,<=50K

*   Min-max scaling is preferred when the distribution of feature values is not necessarily Gaussian and when preserving the relationships between the original values is important.
*   Algorithms where the scale of features doesn't affect the performance significantly, such as decision trees, random forests, and Naive Bayes classifiers.
*   Min-max scaling scales the features to a fixed range, typically [0, 1] or [-1, 1], preserving the shape of the original distribution and the relationships between values.

In [17]:
#Applying one-hot encoding

for col in df.columns:
    if df[col].dtype == 'object' and len(df[col].unique()) < 5:
        df = pd.concat([df, pd.get_dummies(df[col], prefix=col)], axis=1)
        df.drop(col, axis=1, inplace=True)
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male,income_ <=50K,income_ >50K
0,0.301370,State-gov,0.044302,Bachelors,0.800000,Never-married,Adm-clerical,Not-in-family,White,0.02174,0.0,0.397959,United-States,False,True,True,False
1,0.452055,Self-emp-not-inc,0.048238,Bachelors,0.800000,Married-civ-spouse,Exec-managerial,Husband,White,0.00000,0.0,0.122449,United-States,False,True,True,False
2,0.287671,Private,0.138113,HS-grad,0.533333,Divorced,Handlers-cleaners,Not-in-family,White,0.00000,0.0,0.397959,United-States,False,True,True,False
3,0.493151,Private,0.151068,11th,0.400000,Married-civ-spouse,Handlers-cleaners,Husband,Black,0.00000,0.0,0.397959,United-States,False,True,True,False
4,0.150685,Private,0.221488,Bachelors,0.800000,Married-civ-spouse,Prof-specialty,Wife,Black,0.00000,0.0,0.397959,Cuba,True,False,True,False

One-Hot Encoding:

Pros:


*    One-hot encoding preserves all the information about the categorical variable without making any assumptions about the relationships between categories.
*   One-hot encoding creates a format that is compatible with most machine learning algorithms, including linear models, tree-based models, and neural networks.

Cons:


*  One-hot encoding increases the dimensionality of the dataset, especially when dealing with categorical variables with a large number of unique categories. This can lead to a sparse matrix representation and increase computational complexity.
*   One-hot encoding can introduce multicollinearity when there are correlations between categories.

In [18]:
import pandas as pd
df=pd.read_csv("adult_with_headers.csv")

In [19]:
# Label Encoding for categorical variables with more than 5 categories.

categorical_columns = df.select_dtypes(include=['object']).columns

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for column in categorical_columns:
  if len(df[column].unique()) > 5:
    df[column] = le.fit_transform(df[column])

df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,7,77516,9,13,4,1,1,White,Male,2174,0,40,39,<=50K
1,50,6,83311,9,13,2,4,0,White,Male,0,0,13,39,<=50K
2,38,4,215646,11,9,0,6,1,White,Male,0,0,40,39,<=50K
3,53,4,234721,1,7,2,6,0,Black,Male,0,0,40,39,<=50K
4,28,4,338409,9,13,2,10,5,Black,Female,0,0,40,5,<=50K

Label Encoding:

Pros:


*   Label encoding reduces the dimensionality of the dataset by converting categorical variables into integer labels.
*   Label encoding preserves the ordinal relationship between categories, making it suitable for ordinal categorical variables where there is a meaningful order or ranking.

Cons:


*   Label encoding assumes an ordinal relationship between categories, which may not always be appropriate.
*   Some machine learning algorithms may misinterpret the integer labels assigned by label encoding as continuous or ordinal values, leading to incorrect interpretations of the data.

In [20]:
import pandas as pd
df=pd.read_csv("adult_with_headers.csv")

In [22]:
import pandas as pd
# Feature engineering: Creating new features

# 1. Create a new feature called "age_group" by binning the "age" column.
df['age_group'] = pd.cut(df['age'], bins=[16, 25, 35, 45, 55, 65], labels=['16-25', '25-35', '35-45', '45-55', '55-65'])

# 2. Create a new feature called "education_level" by combining the "education" and "education_num" columns.
df['education_level'] = df['education'] + '_' + df['education_num'].astype(str)

# Display the first five rows of the updated DataFrame
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,age_group,education_level
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,35-45,Bachelors_13
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,45-55,Bachelors_13
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,35-45,HS-grad_9
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,45-55,11th_7
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,25-35,Bachelors_13

In [23]:
#apply log transformation to column fnlwgt

import numpy as np
df['fnlwgt'] = np.log(df['fnlwgt'])
df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income,age_group,education_level
0,39,State-gov,11.258240,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,35-45,Bachelors_13
1,50,Self-emp-not-inc,11.330336,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,45-55,Bachelors_13
2,38,Private,12.281393,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,35-45,HS-grad_9
3,53,Private,12.366153,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,45-55,11th_7
4,28,Private,12.732011,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,25-35,Bachelors_13

In [27]:
import pandas as pd
df=pd.read_csv("adult_with_headers.csv")

In [28]:
categorical_columns = df.select_dtypes(include=['object']).columns

le = LabelEncoder()
for column in categorical_columns:
  df[column] = le.fit_transform(df[column])

df.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,7,77516,9,13,4,1,1,4,1,2174,0,40,39,0
1,50,6,83311,9,13,2,4,0,4,1,0,0,13,39,0
2,38,4,215646,11,9,0,6,1,4,1,0,0,40,39,0
3,53,4,234721,1,7,2,6,0,2,1,0,0,40,39,0
4,28,4,338409,9,13,2,10,5,2,0,0,0,40,5,0

In [29]:
# Use of the Isolation Forest algorithm to identify and remove outliers.

from sklearn.ensemble import IsolationForest

# Create an Isolation Forest model
model = IsolationForest(n_estimators=100, contamination='auto')

# Fit the model to the data
model.fit(df)

# Identify outliers
outliers = model.predict(df)

# Remove outliers from the dataframe
df = df[outliers == 1]

In [30]:
# Calculate the PPS matrix
pps_matrix = df.corr().abs()

# Find the top 5 highest PPS values for each feature
for i in range(pps_matrix.shape[0]):
  top_5_pps = pps_matrix.iloc[i].sort_values(ascending=False)[1:6]
  print(f"Top 5 PPS values for feature '{pps_matrix.index[i]}':")
  for feature, pps in top_5_pps.items():
    print(f"\t- {feature}: {pps}")

# Compare PPS findings with the correlation matrix
correlation_matrix = df.corr()

for i in range(correlation_matrix.shape[0]):
  for j in range(i + 1, correlation_matrix.shape[1]):
    feature1 = correlation_matrix.index[i]
    feature2 = correlation_matrix.columns[j]
    pps = pps_matrix.loc[feature1, feature2]
    correlation = correlation_matrix.loc[feature1, feature2]
    if abs(pps - correlation) > 0.1:
      print(f"Significant difference in PPS and correlation for features '{feature1}' and '{feature2}':")
      print(f"\tPPS: {pps}")
      print(f"\tCorrelation: {correlation}")

Top 5 PPS values for feature 'age':
	- marital_status: 0.3639500029566376
	- relationship: 0.3380814402242176
	- income: 0.25229756861717495
	- sex: 0.15204991460959688
	- hours_per_week: 0.1410825730759412
Top 5 PPS values for feature 'workclass':
	- occupation: 0.16439303135568145
	- hours_per_week: 0.09834070930643955
	- relationship: 0.07818725205297783
	- sex: 0.06962325591704051
	- age: 0.056344379532540165
Top 5 PPS values for feature 'fnlwgt':
	- age: 0.08090759033171148
	- native_country: 0.05589614235005363
	- marital_status: 0.041015783552808376
	- sex: 0.029715843976239255
	- race: 0.028155914189944047
Top 5 PPS values for feature 'education':
	- education_num: 0.2725651815390702
	- sex: 0.0694002831797463
	- income: 0.050116251527262276
	- occupation: 0.04657713781427286
	- race: 0.03501449409684719
Top 5 PPS values for feature 'education_num':
	- income: 0.3078964705857494
	- education: 0.2725651815390702
	- hours_per_week: 0.13592580539573712
	- relationship: 0.10768016275907627
	- capital_gain: 0.10179954458701108
Top 5 PPS values for feature 'marital_status':
	- age: 0.3639500029566376
	- relationship: 0.2378947411612512
	- income: 0.20133577087159887
	- hours_per_week: 0.18836560218838955
	- sex: 0.13100082969264845
Top 5 PPS values for feature 'occupation':
	- workclass: 0.16439303135568145
	- education_num: 0.10066777687469712
	- income: 0.06572712194660194
	- relationship: 0.06404933400964961
	- sex: 0.06183519786030306
Top 5 PPS values for feature 'relationship':
	- sex: 0.5623928827539628
	- income: 0.3472916655833041
	- age: 0.3380814402242176
	- hours_per_week: 0.2735594264108208
	- marital_status: 0.2378947411612512
Top 5 PPS values for feature 'race':
	- relationship: 0.10022281979709931
	- income: 0.09996387666892143
	- marital_status: 0.09990844851807959
	- sex: 0.06443497056824318
	- age: 0.05241162746651816
Top 5 PPS values for feature 'sex':
	- relationship: 0.5623928827539628
	- income: 0.2755152480832346
	- hours_per_week: 0.23116042860032238
	- age: 0.15204991460959688
	- marital_status: 0.13100082969264845
Top 5 PPS values for feature 'capital_gain':
	- income: 0.22972183083363698
	- relationship: 0.10365355349113416
	- education_num: 0.10179954458701108
	- age: 0.0862517283125467
	- sex: 0.083158057576034
Top 5 PPS values for feature 'capital_loss':
	- income: 0.09724861873943189
	- relationship: 0.0808656147326235
	- sex: 0.06522841990589165
	- education_num: 0.05494760906990739
	- race: 0.04755402500214375
Top 5 PPS values for feature 'hours_per_week':
	- relationship: 0.2735594264108208
	- sex: 0.23116042860032238
	- income: 0.23024457892211894
	- marital_status: 0.18836560218838955
	- age: 0.1410825730759412
Top 5 PPS values for feature 'native_country':
	- education_num: 0.06054984702050367
	- fnlwgt: 0.05589614235005363
	- income: 0.05154081755293304
	- race: 0.04109396815766293
	- age: 0.03990718195255613
Top 5 PPS values for feature 'income':
	- relationship: 0.3472916655833041
	- education_num: 0.3078964705857494
	- sex: 0.2755152480832346
	- age: 0.25229756861717495
	- hours_per_week: 0.23024457892211894
Significant difference in PPS and correlation for features 'age' and 'fnlwgt':
	PPS: 0.08090759033171148
	Correlation: -0.08090759033171148
Significant difference in PPS and correlation for features 'age' and 'marital_status':
	PPS: 0.3639500029566376
	Correlation: -0.3639500029566376
Significant difference in PPS and correlation for features 'age' and 'relationship':
	PPS: 0.3380814402242176
	Correlation: -0.3380814402242176
Significant difference in PPS and correlation for features 'workclass' and 'marital_status':
	PPS: 0.05040571789215033
	Correlation: -0.05040571789215033
Significant difference in PPS and correlation for features 'workclass' and 'relationship':
	PPS: 0.07818725205297783
	Correlation: -0.07818725205297783
Significant difference in PPS and correlation for features 'fnlwgt' and 'native_country':
	PPS: 0.05589614235005363
	Correlation: -0.05589614235005363
Significant difference in PPS and correlation for features 'education' and 'sex':
	PPS: 0.0694002831797463
	Correlation: -0.0694002831797463
Significant difference in PPS and correlation for features 'education_num' and 'relationship':
	PPS: 0.10768016275907627
	Correlation: -0.10768016275907627
Significant difference in PPS and correlation for features 'marital_status' and 'race':
	PPS: 0.09990844851807959
	Correlation: -0.09990844851807959
Significant difference in PPS and correlation for features 'marital_status' and 'sex':
	PPS: 0.13100082969264845
	Correlation: -0.13100082969264845
Significant difference in PPS and correlation for features 'marital_status' and 'hours_per_week':
	PPS: 0.18836560218838955
	Correlation: -0.18836560218838955
Significant difference in PPS and correlation for features 'marital_status' and 'income':
	PPS: 0.20133577087159887
	Correlation: -0.20133577087159887
Significant difference in PPS and correlation for features 'occupation' and 'relationship':
	PPS: 0.06404933400964961
	Correlation: -0.06404933400964961
Significant difference in PPS and correlation for features 'relationship' and 'race':
	PPS: 0.10022281979709931
	Correlation: -0.10022281979709931
Significant difference in PPS and correlation for features 'relationship' and 'sex':
	PPS: 0.5623928827539628
	Correlation: -0.5623928827539628
Significant difference in PPS and correlation for features 'relationship' and 'capital_gain':
	PPS: 0.10365355349113416
	Correlation: -0.10365355349113416
Significant difference in PPS and correlation for features 'relationship' and 'capital_loss':
	PPS: 0.0808656147326235
	Correlation: -0.0808656147326235
Significant difference in PPS and correlation for features 'relationship' and 'hours_per_week':
	PPS: 0.2735594264108208
	Correlation: -0.2735594264108208
Significant difference in PPS and correlation for features 'relationship' and 'income':
	PPS: 0.3472916655833041
	Correlation: -0.3472916655833041